services:
  esport-syncer:
    build: .
    container_name: esport-syncer
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    volumes:
      - .db:/bin/.db
    environment:
      PANDASCORE_TEAM_ID: ${PANDASCORE_TEAM_ID}
      PANDASCORE_API_KEY: ${PANDASCORE_API_KEY}
      CALENDAR_NAME: ${CALENDAR_NAME}
      CALENDAR_COLOR: ${CALENDAR_COLOR}
      CALENDAR_REFRESH_INTERVAL: ${CALENDAR_REFRESH_INTERVAL}
      SECRET_KEY: ${SECRET_KEY}
      PORT: ${PORT}
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.esport-syncer.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.esport-syncer.entrypoints=web-secure"

networks:
  proxy:
    external: true
