services:
  esport-syncer:
    build: .
    container_name: esport-syncer
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PANDASCORE_TEAM_ID: ${PANDASCORE_TEAM_ID}
      PANDASCORE_API_KEY: ${PANDASCORE_API_KEY}
      CALENDAR_NAME: ${CALENDAR_NAME}
      CALENDAR_COLOR: ${CALENDAR_COLOR}
      CALENDAR_REFRESH_INTERVAL: ${CALENDAR_REFRESH_INTERVAL}
      PORT: ${PORT}
