# Check the health of the service
GET {{url}}/health
Accept: application/json

###

# Get calendar file
GET {{url}}/calendar.ics

###

# Refresh events
POST {{url}}/refresh
Content-Type: application/json
App-Token: wTest100*